##############################################################################
#   @author         :   Rodney Smith
#   @date           :   11/22/2023
#   @package        :   sensors
#   @description    :   Add date & time sensors to Home Assistant
#                          https://www.home-assistant.io/integrations/time_date
###############################################################################
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'