##############################################################################
#   @author         :   Rodney Smith
#   @date           :   11/22/2023
#   @package        :   sensors
#   @description    :   Add door & window sensors to Home Assistant
#                           https://www.home-assistant.io/integrations/template
###############################################################################
- platform: template
  sensors:
    rodney_speed:
      friendly_name: "Rodney Speed"
      unit_of_measurement: 'mph'
      value_template: "{{ state_attr('device_tracker.einstein_iphone', 'speed') | float / 1.609 | round(0) }}"
    rodney_county:
      friendly_name: "Rodney County"
      value_template: "{{ state_attr('sensor.einstein_iphone_geocoded_location', 'Sub Administrative Area') }}"
    gina_speed:
      friendly_name: "Gina Speed"
      unit_of_measurement: 'mph'
      value_template: "{{ state_attr('device_tracker.gina_iphone', 'speed') | float / 1.609 | round(0) }}"
    gina_county:
      friendly_name: "Gina County"
      value_template: "{{ state_attr('sensor.gina_iphone_geocoded_location', 'Sub Administrative Area') }}"

    people_home:
      friendly_name: "People"
      unit_of_measurement: 'home'
      value_template: >
        {{ states['person'] | selectattr('state','eq','home') 
        | list | count }}
    people_away:
      friendly_name: "People"
      unit_of_measurement: 'away'
      value_template: >
        {{ states['person'] | selectattr('state','ne','home') 
        | list | count }}        