##############################################################################
#   @author         :   Rodney Smith
#   @date           :   11/27/2023
#   @package        :   iTunes
#   @description    :   Add iiTunes to Home Assistant
###############################################################################
# media_player.bedroom_echo_dot
# media_player.bedroom_echo_show5
# media_player.guest1_echo_dot
# media_player.guest2_echo_dot
# media_player.hall_echo_flex
# media_player.kitchen_echo_flex
# media_player.lr_echo_show5
# media_player.left_echo
# media_player.right_echo
# media_player.office_echo_show
# media_player.left_echo_dot
# media_player.right_echo_dot

- platform: itunes
  host: 10.0.1.30
