substitutions:
  name: athom-rgbww-light-3f6051
  friendly_name: Side Porch 1
  ip_address: !secret ip_athom_3f6051
  api_key: !secret athom_3f6051

packages:
  athom.rgbww-light: github://athom-tech/athom-configs/athom-rgbww-light.yaml

esphome:
  name: ${name}
  comment: Athon.tech 15W Color Bulb for ESPHome
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip_address}
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet
    dns1: !secret ip_dns
  ap: 
    ssid: ${name}_AP
    password: !secret wifi_ap_pass
    ap_timeout: 3min

api:
  encryption:
    key: ${api_key}
