substitutions:
  name: kauf-bulb-df340e
  friendly_name: Gina's Light

packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret kauf_df340e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret ip_kauf_df340e
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet
    dns1: !secret ip_dns
  ap:
    ssid: ${name}_AP
    password: !secret wifi_ap_pass
    ap_timeout: 3min
