###############################################################################
#   @author         :   Rodney Smith
#   @date           :   10/14/2022
#   @package        :   Announcements
#   @description    :   Daily Announcements.
###############################################################################

################################
# Announcment Automation - fires at the time of the above input_datetimes
################################
automation:

  - id: 81bee5ee-6820-4626-aebf-3deb8de69e4d
    alias: Turn On Audible Notifications
    initial_state: true
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.notify_audible_on', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.notify_audible

  # Turn off audible notifications if they have't been turned off yet.
  - id: e0e9c774-6abe-42aa-bdab-32108bebb0e9
    alias: Turn Off Audible Notifications
    initial_state: true
    trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.notify_audible_off', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    condition:
    - condition: state
      entity_id: input_boolean.notify_audible
      state: 'on'
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.notify_audible

  - id: 1d8f396a-f6ec-460d-97e3-d11900418f95
    alias: Good Morning Report
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_occupied
        to: 'on'
    condition:
      - condition: time
        after: '06:15:00'
        before: '08:30:00'
      - condition: state
        entity_id: input_boolean.report_morning
        state: 'off'
    action:
    - service: script.morning_briefing
      data:
        message: >-
          {{ [ "I just provided a morning briefing including weather, and traffic
          conditions, and other things that ensure the residents of Anchorage House know what to expect today.",
                "Time for the daily update. It was like that scene in Ironman where JARVIS gives the daily briefing but no one was listening. ",
                "I have prepared a safety briefing to present to my residents but they would just ignore it.",
                "Do you like to be prepared for the day? So do my residents. So I provided them with an update on whats happening today.",
                "Sometimes I just like to be snarky, but this morning I decided to just tell everyone what is going on in the world.",
                "#Homeassistant gives me the ability to make daily announcements like the one I just did using #Amazon Polly.",
                "Each day at this time I provide the residents of this house an update that includes everything they need to know about the upcoming day. But with more snark."
              ] | random }}
    - service: input_boolean.turn_on
      entity_id: input_boolean.report_morning

  - id: e8580ba4-fa76-4185-818b-fba3c3cea41c
    alias: Master Bedroom Report
    initial_state: true
    trigger:
      platform: time
      at: input_datetime.report_daily
    condition:
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    action:
    - service: script.morning_wakeup_report
